version: "3.7"
services:  
  main:
    image: main:latest
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      GPG_TTY: /dev/console
    volumes:
      - $HOME/.m2:/root/.m2
      - ./:/app